version: '3'

services:
  io.swagger:
    image: josemottalopes/home-web
    build:
      context: .
      dockerfile: src/IO.Swagger/pi.Dockerfile
    ports:
    - "5010"
    network_mode: bridge
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  home.ui:
    image: josemottalopes/home-ui
    build:
      context: .
      dockerfile: src/Home.UI/pi.Dockerfile
    ports:
    - "80"
    network_mode: bridge
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
 
  ssl.proxy:
    image: josemottalopes/nginx-proxy
    build:
      context: .
      dockerfile: proxy.Dockerfile
    ports:
    - "443"
    network_mode: bridge
